lib/sound_place_web/router.ex
defmodule SoundPlaceWeb.Router do
  use SoundPlaceWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :admin_session do
    plug Guardian.Plug.VerifySession
    plug Guardian.Plug.EnsureAuthenticated, handler: SoundPlaceWeb.SessionController
    plug Guardian.Plug.LoadResource
    plug SoundPlaceWeb.CurrentUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_session do
    plug Guardian.Plug.VerifyHeader, realm: "Bearer"
    plug Guardian.Plug.LoadResource
  end

  scope "/", SoundPlaceWeb do
    pipe_through :browser

    get "/", HomeController, :index

    get "/auth/spotify", AuthController, :spotify
    get "/auth/spotify/callback", AuthController, :callback

    resources "/admin/sessions", SessionController, only: [:new, :create, :delete], singleton: true
  end

  scope "/admin", SoundPlaceWeb.Admin, as: :admin do
    pipe_through [:browser, :admin_session]

    resources "/dashboard", DashboardController, only: [:index]
    resources "/users", UserController, except: [:show, :edit, :update]
    resources "/genres", GenreController, except: [:show]
    resources "/labels", LabelController, except: [:show]
    resources "/album_types", AlbumTypeController, except: [:show]
    resources "/artists", ArtistController, except: [:show] do
      resources "/albums", AlbumController, except: [:show] do
        resources "/tracks", TrackController, except: [:show] do
        end
      end
    end
  end

  scope "/api", SoundPlaceWeb.API, as: :api do
    pipe_through [:api, :api_session]

    get "/me", UserController, :me
    get "/me/playlists", UserController, :playlists
    get "/me/artists", UserController, :artists
    post "/me/import", UserController, :import

    resources "/playlists", PlaylistController, only: [] do
      get "/tracks", PlaylistController, :tracks
    end
  end
end

lib/sound_place_web/views/layout_view.ex
defmodule SoundPlaceWeb.LayoutView do
  use SoundPlaceWeb, :view
end

lib/sound_place_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>.:: Sound Place ::.</title>

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <main class="wrapper">

      <nav class="navigation">
        <section class="container">
          <%= link(to: admin_dashboard_path(@conn, :index), class: "navigation-title") do %>
            <h1 class="title">Sound Place</h1>
          <% end %>

          <ul class="navigation-list float-right">
            <li class="navigation-item">
              <%= link("Dashboard",
                       to: admin_dashboard_path(@conn, :index),
                       class: "navigation-link") %>
            </li>

            <li class="navigation-item">
              <a class="navigation-link" href="#popover-grid" data-popover="">Media</a>
              <div class="popover" id="popover-grid">
                <ul class="popover-list">
                  <li class="popover-item">
                    <%= link("Album types",
                             to: admin_album_type_path(@conn, :index),
                             class: "popover-link",
                             title: "Album types") %>
                  </li>

                  <li class="popover-item">
                    <%= link("Artists",
                             to: admin_artist_path(@conn, :index),
                             class: "popover-link",
                             title: "Artists") %>
                  </li>

                  <li class="popover-item">
                    <%= link("Genres",
                             to: admin_genre_path(@conn, :index),
                             class: "popover-link",
                             title: "Genres") %>
                  </li>

                  <li class="popover-item">
                    <%= link("Labels",
                             to: admin_label_path(@conn, :index),
                             class: "popover-link",
                             title: "Labels") %>
                  </li>
                </ul>
              </div>
            </li>

            <li class="navigation-item">
              <%= link("Users",
                       to: admin_user_path(@conn, :index),
                       class: "navigation-link") %>
            </li>

            <li class="navigation-item">
              <%= link("Sign out",
                       to: session_path(@conn, :delete),
                       class: "navigation-link",
                       method: :delete,
                       data: [confirm: "Are you sure?"]) %>
            </li>
          </ul>
        </section>
      </nav>

      <section class="container">
        <div class="row">
          <div class="column">
            <%= render "messages.html", conn: @conn %>
          </div>
        </div>

        <div class="row">
          <div class="column">
            <%= render @view_module, @view_template, assigns %>
          </div>
        </div>
      </section>

      <footer class="footer">
        <section class="container">
          <p>Designed by Sound Place.</p>
        </section>
      </footer>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>
      require("js/app").App.run()
    </script>
  </body>
</html>

lib/sound_place_web/templates/layout/messages.html.eex
<% info = get_flash(@conn, :info) %>
<%= if info do %>
  <p class="alert alert-info"><%= info %></p>
<% end %>

<% error = get_flash(@conn, :error) %>
<%= if error do %>
  <p class="alert alert-danger"><%= error %></p>
<% end %>

lib/sound_place_web/templates/layout/sign_in.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>.:: Sound Place ::.</title>

    <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Roboto:300,300italic,700,700italic">
    <link rel="stylesheet" href="//cdn.rawgit.com/necolas/normalize.css/master/normalize.css">

    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <main class="wrapper">

      <nav class="navigation">
        <section class="container">
          <%= link(to: admin_dashboard_path(@conn, :index), class: "navigation-title sign-in-navigation-logo") do %>
            <h1 class="title">Sound Place</h1>
          <% end %>
        </section>
      </nav>

      <section class="container">
        <div class="row">
          <div class="column column-50 column-offset-25">
            <%= render "messages.html", conn: @conn %>
          </div>
        </div>

        <div class="row">
          <div class="column column-50 column-offset-25">
            <%= render @view_module, @view_template, assigns %>
          </div>
        </div>
      </section>
    </main>

    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
    <script>
      require("js/app").App.run()
    </script>
  </body>
</html>